import 'package:flutter/material.dart';
import 'package:mirai/src/SM/sm_stac_theme_extension.dart';
import 'package:mirai/src/utils/color_type.dart';

extension ColorExt on String? {
  Color? toColor(BuildContext context) {
    if (this?.isEmpty ?? true) return null;
    final themeExtension = Theme.of(context).extension<SMStacThemeExtension>();
    switch (colorType) {
      case ColorType.primary:
        return Theme.of(context).colorScheme.primary;
      case ColorType.onPrimary:
        return Theme.of(context).colorScheme.onPrimary;
      case ColorType.primaryContainer:
        return Theme.of(context).colorScheme.primaryContainer;
      case ColorType.onPrimaryContainer:
        return Theme.of(context).colorScheme.onPrimaryContainer;
      case ColorType.secondary:
        return Theme.of(context).colorScheme.secondary;
      case ColorType.onSecondary:
        return Theme.of(context).colorScheme.onSecondary;
      case ColorType.secondaryContainer:
        return Theme.of(context).colorScheme.secondaryContainer;
      case ColorType.onSecondaryContainer:
        return Theme.of(context).colorScheme.onSecondaryContainer;
      case ColorType.tertiary:
        return Theme.of(context).colorScheme.tertiary;
      case ColorType.onTertiary:
        return Theme.of(context).colorScheme.onTertiary;
      case ColorType.tertiaryContainer:
        return Theme.of(context).colorScheme.tertiaryContainer;
      case ColorType.onTertiaryContainer:
        return Theme.of(context).colorScheme.onTertiaryContainer;
      case ColorType.error:
        return Theme.of(context).colorScheme.error;
      case ColorType.onError:
        return Theme.of(context).colorScheme.onError;
      case ColorType.errorContainer:
        return Theme.of(context).colorScheme.errorContainer;
      case ColorType.onErrorContainer:
        return Theme.of(context).colorScheme.onErrorContainer;
      case ColorType.background:
        return Theme.of(context).colorScheme.background;
      case ColorType.onBackground:
        return Theme.of(context).colorScheme.onBackground;
      case ColorType.surface:
        return Theme.of(context).colorScheme.surface;
      case ColorType.onSurface:
        return Theme.of(context).colorScheme.onSurface;
      case ColorType.surfaceVariant:
        return Theme.of(context).colorScheme.surfaceVariant;
      case ColorType.onSurfaceVariant:
        return Theme.of(context).colorScheme.onSurfaceVariant;
      case ColorType.outline:
        return Theme.of(context).colorScheme.outline;
      case ColorType.outlineVariant:
        return Theme.of(context).colorScheme.outlineVariant;
      case ColorType.shadow:
        return Theme.of(context).colorScheme.shadow;
      case ColorType.scrim:
        return Theme.of(context).colorScheme.scrim;
      case ColorType.inverseSurface:
        return Theme.of(context).colorScheme.inverseSurface;
      case ColorType.onInverseSurface:
        return Theme.of(context).colorScheme.onInverseSurface;
      case ColorType.inversePrimary:
        return Theme.of(context).colorScheme.inversePrimary;
      case ColorType.surfaceTint:
        return Theme.of(context).colorScheme.surfaceTint;
      case ColorType.scaffoldBackgroundColor:
        return Theme.of(context).scaffoldBackgroundColor;
      case ColorType.selectedRowColor:
        return themeExtension?.selectedRowColor;
      case ColorType.bottomAppBarColor:
        return themeExtension?.bottomAppBarColor;

      case ColorType.advertiseOrVerifyBottomSheetCTA:
        return themeExtension?.advertiseOrVerifyBottomSheetCTA;
      case ColorType.advertiseOrVerifyBottomSheetDivider:
        return themeExtension?.advertiseOrVerifyBottomSheetDivider;
      case ColorType.advertiseOrVerifyBottomSheetIconItem:
        return themeExtension?.advertiseOrVerifyBottomSheetIconItem;
      case ColorType.advertiseOrVerifyBottomSheetLaterTextButton:
        return themeExtension?.advertiseOrVerifyBottomSheetLaterTextButton;
      case ColorType.albumCommentIconColor:
        return themeExtension?.albumCommentIconColor;
      case ColorType.albumCommentTextColor:
        return themeExtension?.albumCommentTextColor;
      case ColorType.mediaFavoriteIconColor:
        return themeExtension?.mediaFavoriteIconColor;
      case ColorType.albumOptionsIconColor:
        return themeExtension?.albumOptionsIconColor;
      case ColorType.albumDownloadIconColor:
        return themeExtension?.albumDownloadIconColor;
      case ColorType.albumPageDividerColor:
        return themeExtension?.albumPageDividerColor;
      case ColorType.mediaNotReleasedHeaderTitle:
        return themeExtension?.mediaNotReleasedHeaderTitle;
      case ColorType.mediaNotReleasedBody:
        return themeExtension?.mediaNotReleasedBody;
      case ColorType.mediaNotReleasedDivider:
        return themeExtension?.mediaNotReleasedDivider;
      case ColorType.mediaNotReleasedCTA:
        return themeExtension?.mediaNotReleasedCTA;
      case ColorType.albumInfoBottomSheetTitle:
        return themeExtension?.albumInfoBottomSheetTitle;
      case ColorType.albumInfoBottomSheetThumbnailTitle:
        return themeExtension?.albumInfoBottomSheetThumbnailTitle;
      case ColorType.albumInfoBottomSheetThumbnailContent:
        return themeExtension?.albumInfoBottomSheetThumbnailContent;
      case ColorType.albumInfoBottomSheetPublishedTitle:
        return themeExtension?.albumInfoBottomSheetPublishedTitle;
      case ColorType.albumInfoBottomSheetPublishedContent:
        return themeExtension?.albumInfoBottomSheetPublishedContent;
      case ColorType.albumInfoBottomSheetSizeTitle:
        return themeExtension?.albumInfoBottomSheetSizeTitle;
      case ColorType.albumInfoBottomSheetSizeContent:
        return themeExtension?.albumInfoBottomSheetSizeContent;
      case ColorType.albumInfoBottomSheetMusicStyleTitle:
        return themeExtension?.albumInfoBottomSheetMusicStyleTitle;
      case ColorType.artistNameColor:
        return themeExtension?.artistNameColor;
      case ColorType.bannerLibraryColor:
        return themeExtension?.bannerLibraryColor;
      case ColorType.chatUserMessageColor:
        return themeExtension?.chatUserMessageColor;
      case ColorType.commonCardBackgroundColor:
        return themeExtension?.commonCardBackgroundColor;
      case ColorType.chatWriteMessageBackgroundColor:
        return themeExtension?.chatWriteMessageBackgroundColor;
      case ColorType.chatWriteMessageTextAndFieldColor:
        return themeExtension?.chatWriteMessageTextAndFieldColor;
      case ColorType.createOrEditPlaylistBackgroundColor:
        return themeExtension?.createOrEditPlaylistBackgroundColor;
      case ColorType.discoverySuggestionItem:
        return themeExtension?.discoverySuggestionItem;
      case ColorType.editMoreInformationBackgroundColor:
        return themeExtension?.editMoreInformationBackgroundColor;
      case ColorType.positiveButtonDescriptionColor:
        return themeExtension?.positiveButtonDescriptionColor;
      case ColorType.positiveButtonBackgroundColor:
        return themeExtension?.positiveButtonBackgroundColor;
      case ColorType.negativeButtonTextColor:
        return themeExtension?.negativeButtonTextColor;
      case ColorType.popupTextColor:
        return themeExtension?.popupTextColor;
      case ColorType.popupNotNowTextColor:
        return themeExtension?.popupNotNowTextColor;
      case ColorType.itemSelectedColor:
        return themeExtension?.itemSelectedColor;
      case ColorType.itemMusicInfoTextColor:
        return themeExtension?.itemMusicInfoTextColor;
      case ColorType.itemMusicOptionsIconColor:
        return themeExtension?.itemMusicOptionsIconColor;
      case ColorType.itemMusicAddIconColor:
        return themeExtension?.itemMusicAddIconColor;
      case ColorType.itemNumberAnimationColor:
        return themeExtension?.itemNumberAnimationColor;
      case ColorType.recommendedUsernameMediaFontColor:
        return themeExtension?.recommendedUsernameMediaFontColor;
      case ColorType.preRollFontBorderColor:
        return themeExtension?.preRollFontBorderColor;
      case ColorType.vividCeruleanToBrandMedium:
        return themeExtension?.vividCeruleanToBrandMedium;
      case ColorType.preSearchNewsSection:
        return themeExtension?.preSearchNewsSection;
      case ColorType.preSearchNewsDate:
        return themeExtension?.preSearchNewsDate;
      case ColorType.preSearchTitle:
        return themeExtension?.preSearchTitle;
      case ColorType.preSearchIcons:
        return themeExtension?.preSearchIcons;
      case ColorType.helpCenterTextColor:
        return themeExtension?.helpCenterTextColor;
      case ColorType.helpCenterTitleColor:
        return themeExtension?.helpCenterTitleColor;
      case ColorType.reportAppBarColor:
        return themeExtension?.reportAppBarColor;
      case ColorType.reportAppBarTextColor:
        return themeExtension?.reportAppBarTextColor;
      case ColorType.reportAppBarBackgroundColor:
        return themeExtension?.reportAppBarBackgroundColor;
      case ColorType.reportProblemFieldTextColor:
        return themeExtension?.reportProblemFieldTextColor;
      case ColorType.reportProblemTextStyleColor:
        return themeExtension?.reportProblemTextStyleColor;
      case ColorType.reportProblemTextButtonColor:
        return themeExtension?.reportProblemTextButtonColor;
      case ColorType.reportProblemErrorTextColor:
        return themeExtension?.reportProblemErrorTextColor;
      case ColorType.reportProblemTitleTextColor:
        return themeExtension?.reportProblemTitleTextColor;
      case ColorType.reportTileIconColor:
        return themeExtension?.reportTileIconColor;
      case ColorType.reportDropdownIconColor:
        return themeExtension?.reportDropdownIconColor;
      case ColorType.reportDropdownBorderColor:
        return themeExtension?.reportDropdownBorderColor;
      case ColorType.reportDropdownHighlightColor:
        return themeExtension?.reportDropdownHighlightColor;
      case ColorType.reportCheckBoxUnselectedColor:
        return themeExtension?.reportCheckBoxUnselectedColor;
      case ColorType.recommendedItemFontColor:
        return themeExtension?.recommendedItemFontColor;
      case ColorType.selectAllTextColor:
        return themeExtension?.selectAllTextColor;
      case ColorType.successReportPageTextColor:
        return themeExtension?.successReportPageTextColor;
      case ColorType.shareContentViewColor:
        return themeExtension?.shareContentViewColor;
      case ColorType.smInkWellColor:
        return themeExtension?.smInkWellColor;
      case ColorType.bubbleDeleteWidgetColor:
        return themeExtension?.bubbleDeleteWidgetColor;
      case ColorType.libraryStylePremiumColor:
        return themeExtension?.libraryStylePremiumColor;
      case ColorType.loginWithoutPassSendTextColor:
        return themeExtension?.loginWithoutPassSendTextColor;
      case ColorType.myAlbumTextColor:
        return themeExtension?.myAlbumTextColor;
      case ColorType.myAlbumButtonBorderColor:
        return themeExtension?.myAlbumButtonBorderColor;
      case ColorType.myAlbumFillColor:
        return themeExtension?.myAlbumFillColor;
      case ColorType.myPlaylistsPageFillColor:
        return themeExtension?.myPlaylistsPageFillColor;
      case ColorType.playerPageButtonColor:
        return themeExtension?.playerPageButtonColor;
      case ColorType.profileLoadedColor:
        return themeExtension?.profileLoadedColor;
      case ColorType.topsPageLabelColor:
        return themeExtension?.topsPageLabelColor;
      case ColorType.uploadButtonColor:
        return themeExtension?.uploadButtonColor;
      case ColorType.uploadQuestionBackgroundColor:
        return themeExtension?.uploadQuestionBackgroundColor;
      case ColorType.uploadTabColor:
        return themeExtension?.uploadTabColor;
      case ColorType.usernameColor:
        return themeExtension?.usernameColor;
      case ColorType.dateColor:
        return themeExtension?.dateColor;
      case ColorType.hintCommentColor:
        return themeExtension?.hintCommentColor;
      case ColorType.limitCharacterColor:
        return themeExtension?.limitCharacterColor;
      case ColorType.borderInativeColor:
        return themeExtension?.borderInativeColor;
      case ColorType.avatarColor:
        return themeExtension?.avatarColor;
      case ColorType.bottomSheetWithIconsColor:
        return themeExtension?.bottomSheetWithIconsColor;
      case ColorType.bottomSheetWithIconsTitleColor:
        return themeExtension?.bottomSheetWithIconsTitleColor;
      case ColorType.dividerBottomSheetColor:
        return themeExtension?.dividerBottomSheetColor;
      case ColorType.titleShareVertical:
        return themeExtension?.titleShareVertical;
      case ColorType.trailingShareVertical:
        return themeExtension?.trailingShareVertical;
      case ColorType.usernameShareVertical:
        return themeExtension?.usernameShareVertical;
      case ColorType.moreShareIconColor:
        return themeExtension?.moreShareIconColor;
      case ColorType.mediaSearchEmptyQueryColor:
        return themeExtension?.mediaSearchEmptyQueryColor;
      case ColorType.mediaSearchWithoutPlaylist:
        return themeExtension?.mediaSearchWithoutPlaylist;
      case ColorType.myPlaylistsTitlePlaylist:
        return themeExtension?.myPlaylistsTitlePlaylist;
      case ColorType.myPlaylistsNumberOfMusics:
        return themeExtension?.myPlaylistsNumberOfMusics;
      case ColorType.myPlaylistsIconButton:
        return themeExtension?.myPlaylistsIconButton;
      case ColorType.myPlaylistsCursorColor:
        return themeExtension?.myPlaylistsCursorColor;
      case ColorType.myPlaylistsIconSearch:
        return themeExtension?.myPlaylistsIconSearch;
      case ColorType.myPlaylistsClearSearchButton:
        return themeExtension?.myPlaylistsClearSearchButton;
      case ColorType.segmentedBubbleIconColor:
        return themeExtension?.segmentedBubbleIconColor;
      case ColorType.segmentedBubbleTextColor:
        return themeExtension?.segmentedBubbleTextColor;
      case ColorType.createPlaylistText:
        return themeExtension?.createPlaylistText;
      case ColorType.createPlaylistTextFieldBorder:
        return themeExtension?.createPlaylistTextFieldBorder;
      case ColorType.createPlaylistTextFieldHint:
        return themeExtension?.createPlaylistTextFieldHint;
      case ColorType.editPlaylistTextFieldBorder:
        return themeExtension?.editPlaylistTextFieldBorder;
      case ColorType.editPlaylistTextFieldHint:
        return themeExtension?.editPlaylistTextFieldHint;
      case ColorType.editPlaylistWithoutMusicsBody:
        return themeExtension?.editPlaylistWithoutMusicsBody;
      case ColorType.bottomSheetFilterTitleText:
        return themeExtension?.bottomSheetFilterTitleText;
      case ColorType.bottomSheetFilterItemUnselectedText:
        return themeExtension?.bottomSheetFilterItemUnselectedText;
      case ColorType.bottomSheetWithIconsOrderTitleText:
        return themeExtension?.bottomSheetWithIconsOrderTitleText;
      case ColorType.bottomSheetWithIconsOrderItemText:
        return themeExtension?.bottomSheetWithIconsOrderItemText;
      case ColorType.bottomSheetPremiumAccentColor:
        return themeExtension?.bottomSheetPremiumAccentColor;
      case ColorType.bottomSheetPremiumHeaderTitleColor:
        return themeExtension?.bottomSheetPremiumHeaderTitleColor;
      case ColorType.bottomSheetPremiumHeaderDescriptionColor:
        return themeExtension?.bottomSheetPremiumHeaderDescriptionColor;
      case ColorType.playlistPageUsernameColor:
        return themeExtension?.playlistPageUsernameColor;
      case ColorType.playlistEmptyPage:
        return themeExtension?.playlistEmptyPage;
      case ColorType.lowPureToBrandPure:
        return themeExtension?.lowPureToBrandPure;
      case ColorType.lowPureToLowMedium:
        return themeExtension?.lowPureToLowMedium;
      case ColorType.highLightToLowPure:
        return themeExtension?.highLightToLowPure;
      case ColorType.highPureToBrandMedium:
        return themeExtension?.highPureToBrandMedium;
      case ColorType.highPureToBlack:
        return themeExtension?.highPureToBlack;
      case ColorType.highPureToBrandPure:
        return themeExtension?.highPureToBrandPure;
      case ColorType.brandPureToHighPure:
        return themeExtension?.brandPureToHighPure;
      case ColorType.lowMediumToWhite:
        return themeExtension?.lowMediumToWhite;
      case ColorType.lowPureToHighPure:
        return themeExtension?.lowPureToHighPure;
      case ColorType.white15ToSpanishGrey50:
        return themeExtension?.white15ToSpanishGrey50;
      case ColorType.black26ToSpanishGrey50:
        return themeExtension?.black26ToSpanishGrey50;
      case ColorType.neutralHighLightToNeutralLowMedium:
        return themeExtension?.neutralHighLightToNeutralLowMedium;
      case ColorType.brightSilverToFilmProBlack:
        return themeExtension?.brightSilverToFilmProBlack;
      case ColorType.none:
        final buffer = StringBuffer();
        if (this!.length == 6 || this!.length == 7) buffer.write('ff');
        buffer.write(this!.replaceFirst('#', ''));
        int? intColor = int.tryParse(buffer.toString(), radix: 16);
        intColor = intColor ?? 0x00000000;
        return Color(intColor);
    }
  }

  ColorType get colorType => ColorType.values.firstWhere(
        (e) => e.name == this,
        orElse: () => ColorType.none,
      );
}
