name: stac_cli
description: "A CLI tool for building STAC DSL files into JSON format."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  analyzer: ^8.1.1
  dart_style: ^3.1.2
  path: ^1.9.0
  io: ^1.0.4
  http: ^1.2.0
  stac_models: ^0.0.1

dev_dependencies:
  test: ^1.25.8
  lints: ^6.0.0

executables:
  stac: stac_cli
